StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60F284C34C2BF591}" {
   Id "SPC-Vehicle_T72A_Name"
   Target_en_us "T-72A Main Battle Tank"
   Modified 1626510298
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{60F284C3516FCDD0}" {
   Id "SPC-Vehicle_T72B_Name"
   Target_en_us "T-72B Main Battle Tank"
   Modified 1626510296
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
 }
}